// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain


int width;
Texture2D<float4> Glare;
RWStructuredBuffer<float> Result;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    int index = id.x + id.y * width;    
    float v = Glare.Load(int3(id.xy,0)).r;
    if (v < 0)
    {
        v = 0;
    }
       
    Result[index] = v;
}
